name: snazzy_spelling
description: "Snazzy Spelling - A spelling practice app for children"
publish_to: 'none'
version: 1.0.10+11

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_tts: ^4.2.1
  crypto: ^3.0.6
  intl: ^0.20.2
  provider: ^6.1.4
  audioplayers: ^6.1.0
  android_intent_plus: ^6.0.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
